[build]
  base = "/"
  publish = "public/"
  command = "yarn run build"
  functions = "./functions"

[build.environment]

[context.staging.environment]

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    "X-Content-Type-Options" = "nosniff"
    "Referrer-Policy" = "no-referrer, strict-origin-when-cross-origin"

[[headers]]
  for = "/sw.js"
  [headers.values]
    cache-control = "max-age=0,no-cache,no-store,must-revalidate"
